name: Java CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Cache Maven packages
      id: cache-maven-packages
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: maven-repo-cache-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          maven-repo-cache-

    - name: Download Maven Dependencies
      if: steps.cache-maven-packages.outputs.cache-hit != 'true'
      run: ./mvnw dependency:go-offline

    - name: Build with Maven
      run: ./mvnw -o package
